### ISSUE TITLE
Generel udvidelse - I første omgang til håndtering af datasættet "Beskyttet natur" (§ 3 områder) 

### ISSUE THREAD

**Issue by Geodataodense** [bvthomsen/QGIS-DMP-plugin#4]
Plugin'et udvikles p.t. med henblik på  "Regionernes revision af råstof-temaet". Som kommune ønsker en mere generel funktionalitet! 
Funktionaliteten skal understøtte kommunernes revision af datasæt i Miljøportalen. I første omgang skal plugin´et kunne håndtere temaet _Beskyttet natur_

Funktionaliteten skal være den samme som det, der i dag tilbydes i Miljøportalens websnitflade.
Funktionaliteten skal derudover gøre det muligt at foretage masse-udtræk, masse-upload og validering.

Beskyttet natur (og andre datasæt) har en anden datamodel. Der kan være behov for specifik validering på flere attributter. V kommer med yderligere input, når vi kender funktionaliteten for 'råstoffer'. 👍

**Comment by bvthomsen** [comment]
Alle temaer, som kan downloades fra DMP via api kan nu downloades og benyttes i plugin
