### ISSUE TITLE
Generel udvidelse - Geometrivalidering

### ISSUE THREAD

**Issue by RomanHVarinsky** [bvthomsen/QGIS-DMP-plugin#6]
Pluginnet skal kunne validere objektets geometri, så ugyldig geometri ikke kunne uploades tilbage til DMP.
Eksempler på geometrivalidering:
- Fejl ved selvskæring
- Fejl ved dobbel-knudepunkter
- Fejl ved overlap (medmindre det er tilladt ved nogle objekttyper)
- Fejl ved upræcis snap (f.eks. afstand mellem objekterne er mindre end 10cm)
- Krav om objektets minimumstørrelse (f.eks. objekt er mindre end 5m²). Findes der sådan et krav i specifikationen?

**Comment by bvthomsen** [comment]
Løst ved at brugere for adgang til indbygget geometritjekker fra plugin brugerflade
